language: python
python:
  - "2.7"
cache: pip

services:
  - postgresql
  - elasticsearch
env:
  global:
     - DJANGO_TEST_TEMP_DIR=$TRAVIS_BUILD_DIR/
  matrix:
     - DJANGO_VERSION=1.8.4
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"

before_script:
  - psql -c "CREATE DATABASE hiretech;" -U postgres
  - sleep 10

# command to run tests
script:
  - cd hiretech
  - python manage.py test --settings=hiretech.settings.ci
  - coverage run --source=accounts manage.py test --settings=hiretech.settings.ci
  - coverage run --source=hiretech manage.py test --settings=hiretech.settings.ci
  - coverage run --source=companies manage.py test --settings=hiretech.settings.ci
  - coverage run --source=jobs manage.py test --settings=hiretech.settings.ci
  - coverage run --source=search manage.py test --settings=hiretech.settings.ci
  - coverage run --source=users manage.py test --settings=hiretech.settings.ci
  - coverage run --source=posts manage.py test --settings=hiretech.settings.ci

after_success:
  - coveralls
