language: python
python:
  - "2.7"
env:
  matrix:
     - DJANGO_VERSION=1.8.4
# command to install dependencies
install:
  - "pip install -r requirements.txt"
# command to run tests
script:
  - python thirtysevenjobs/manage.py test
