language: python
python:
  - "2.7"
services:

services:
  - postgresql
  - elasticsearch
env:
  global:
     - DJANGO_TEST_TEMP_DIR=$TRAVIS_BUILD_DIR/
  matrix:
     - DJANGO_VERSION=1.8.4
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - 'pip install django-haystack'
  - "pip install coveralls"

before_script:
  - psql -c "CREATE DATABASE gitjobs;" -U postgres
  - sleep 10

# command to run tests
script:
  - cd gitjobs
  - python manage.py test --settings=gitjobs.settings.ci
  - coverage run --source=gitjobs manage.py test --settings=gitjobs.settings.ci
  - coverage run --source=jobs manage.py test --settings=gitjobs.settings.ci
  - coverage run --source=companies manage.py test --settings=gitjobs.settings.ci
  - coverage run --source=users manage.py test --settings=gitjobs.settings.ci

after_success:
  - coveralls
