language: python
python:
  - "2.7"
services: postgresql

env:
  global:
     - DJANGO_TEST_TEMP_DIR=$TRAVIS_BUILD_DIR/
  matrix:
     - DJANGO_VERSION=1.8.4
# command to install dependencies
install:
  - "pip install -r requirements.txt"

before_script:
  - psql -c "CREATE DATABASE gitjobs;" -U postgres

# command to run tests
script:
  - cd thirtysevenjobs
  - python manage.py test

after_success:
  - coveralls
